# Change the default prompt format
format = """\
[â•­â•´](245)$env_var $all\
[â•°â”€](245)$character"""

# Change the default prompt characters
[character]
success_symbol = "[ï”](245)"
error_symbol = "[ï‘§](245)"

# Shows an icon that should be included by zshrc script based on the distribution or os
[env_var.STARSHIP_DISTRO]
format = '[$env_value](bold 178) '  # removed space between distro and rest for pwsh
variable = "STARSHIP_DISTRO"
disabled = false

# Shows the username
[username]
style_user = "bold 178"
style_root = "red"
format = "[$user]($style) "
disabled = false
show_always = true

[hostname]
ssh_only = false
format = "on [$hostname](cyan) "
disabled = false

[directory]
truncation_length = 1
truncation_symbol = "../"
home_symbol = "ï€• ~"
read_only_style = "197"
read_only = " ï€£ "
format = "at [$path]($style)[$read_only]($read_only_style) "

[git_branch]
symbol = "ó°˜¬ "
format = "[$symbol$branch]($style) "
# truncation_length = 4
truncation_symbol = "â€¦/"
style = "bold green"

[git_status]
format = '[\($all_status$ahead_behind\)]($style) '
style = "bold green"
conflicted = "ğŸ³"
up_to_date = "ï† "
untracked = "ï”© "
ahead = "â‡¡${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind = "â‡£${count}"
stashed = "ó°©³ "
modified = "ï„ "
staged = '[++\($count\)](green)'
renamed = "ó°‘• "
deleted = "ï€” "






